# Generated by Django 2.1.3 on 2018-11-06 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Affiliation_sublevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Affiliations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Author_of',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Author_of_external',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Degrees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='External_authors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('last_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='External_citation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='External_publications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doi', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Grant_participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Grants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Group_member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Internal_citation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Journals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('issn', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('last_name', models.TextField()),
                ('orcid', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('affiliation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Affiliations')),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Degrees')),
            ],
        ),
        migrations.CreateModel(
            name='PNPC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Postdocs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Persons')),
            ],
        ),
        migrations.CreateModel(
            name='Program_tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Persons')),
            ],
        ),
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('affiliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Affiliations')),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Degrees')),
                ('pnpc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.PNPC')),
            ],
        ),
        migrations.CreateModel(
            name='Publication_subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('volume', models.IntegerField()),
                ('issue', models.IntegerField()),
                ('date', models.DateField()),
                ('doi', models.TextField()),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Journals')),
            ],
        ),
        migrations.CreateModel(
            name='Researchers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Persons')),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SNI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student_in',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Programs')),
            ],
        ),
        migrations.CreateModel(
            name='Student_of',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Persons')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Roles')),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='student_of',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Students'),
        ),
        migrations.AddField(
            model_name='student_of',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Researchers'),
        ),
        migrations.AddField(
            model_name='student_in',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Students'),
        ),
        migrations.AddField(
            model_name='researchers',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Roles'),
        ),
        migrations.AddField(
            model_name='publication_subject',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Publications'),
        ),
        migrations.AddField(
            model_name='publication_subject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Subjects'),
        ),
        migrations.AddField(
            model_name='program_tutor',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Programs'),
        ),
        migrations.AddField(
            model_name='postdocs',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Roles'),
        ),
        migrations.AddField(
            model_name='persons',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Roles'),
        ),
        migrations.AddField(
            model_name='persons',
            name='sni',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.SNI'),
        ),
        migrations.AddField(
            model_name='persons',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.States'),
        ),
        migrations.AddField(
            model_name='internal_citation',
            name='cited',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cited', to='core.Publications'),
        ),
        migrations.AddField(
            model_name='internal_citation',
            name='citing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citing', to='core.Publications'),
        ),
        migrations.AddField(
            model_name='groups',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Persons'),
        ),
        migrations.AddField(
            model_name='group_member',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Groups'),
        ),
        migrations.AddField(
            model_name='group_member',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Persons'),
        ),
        migrations.AddField(
            model_name='grants',
            name='responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Researchers'),
        ),
        migrations.AddField(
            model_name='grant_participant',
            name='grant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Grants'),
        ),
        migrations.AddField(
            model_name='grant_participant',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Persons'),
        ),
        migrations.AddField(
            model_name='external_citation',
            name='cited',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Publications'),
        ),
        migrations.AddField(
            model_name='external_citation',
            name='citing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.External_publications'),
        ),
        migrations.AddField(
            model_name='author_of_external',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.External_authors'),
        ),
        migrations.AddField(
            model_name='author_of_external',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Publications'),
        ),
        migrations.AddField(
            model_name='author_of',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Persons'),
        ),
        migrations.AddField(
            model_name='author_of',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Publications'),
        ),
        migrations.AddField(
            model_name='affiliation_sublevel',
            name='sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='core.Affiliations'),
        ),
        migrations.AddField(
            model_name='affiliation_sublevel',
            name='super',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='super', to='core.Affiliations'),
        ),
        migrations.AddField(
            model_name='administrators',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Persons'),
        ),
        migrations.AddField(
            model_name='administrators',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Roles'),
        ),
        migrations.AlterUniqueTogether(
            name='student_of',
            unique_together={('student', 'tutor')},
        ),
        migrations.AlterUniqueTogether(
            name='student_in',
            unique_together={('student', 'program')},
        ),
        migrations.AlterUniqueTogether(
            name='publication_subject',
            unique_together={('publication', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='program_tutor',
            unique_together={('person', 'program')},
        ),
        migrations.AlterUniqueTogether(
            name='internal_citation',
            unique_together={('cited', 'citing')},
        ),
        migrations.AlterUniqueTogether(
            name='group_member',
            unique_together={('group', 'person')},
        ),
        migrations.AlterUniqueTogether(
            name='grant_participant',
            unique_together={('person', 'grant')},
        ),
        migrations.AlterUniqueTogether(
            name='external_citation',
            unique_together={('cited', 'citing')},
        ),
        migrations.AlterUniqueTogether(
            name='author_of_external',
            unique_together={('author', 'publication')},
        ),
        migrations.AlterUniqueTogether(
            name='author_of',
            unique_together={('person', 'publication')},
        ),
        migrations.AlterUniqueTogether(
            name='affiliation_sublevel',
            unique_together={('super', 'sub')},
        ),
    ]
